### ISSUE TITLE
How can i add bookmarks?

### ISSUE THREAD

**Issue by Asteroth2018** [maxhu08/mtab#1]
Hello Im on linux and ive went to my .config chromium extensions folder and found the css and html and js files for your extension but there are so many files i cant find where is the bookmarks? i wanted to add 4 more at the bottom of the 4 youve made And im not a programmer i just know how to do css json etc. config files im like newb programmer. Is there even a way to add 4 more bookmarks? And if yes which file is responsible for it.

**Comment by maxhu08** [comment]
It's kind of complicated. Everything is stored in a object in chrome storage, including bookmarks. Then bookmarks are dynamically added to the new tab page through the `renderUserDefinedBookmarks` function in src/newtab/scripts/utils/render-bookmarks.ts.

I'm planning to add the ability to add more than four bookmarks. If you can wait for the next update, you won't need to edit the extension.

**Comment by maxhu08** [comment]
I added the ability to add and remove bookmarks, you can now have any amount of bookmarks you want as of mtab-v1.0.5. I uploaded the new version, but it may take some time for the chrome and firefox webstore to verify it. You may also need to uninstall and reinstall because the structure of the config changed.
