### ISSUE TITLE
Visual bug on Windows

### ISSUE THREAD

**Issue by vaygr** [maxhu08/mtab#8]
After refresh and pointing the cursor to the right of the bar, the first two bookmarks have flickering stripes at the top. Couldn't reproduce it on Linux. Browser is the same - latest Waterfox. Visible only with glass style.

![Wire 2024-07-13 at 14-10-39](https://github.com/user-attachments/assets/745909b5-aceb-4c81-8bc7-e84fc98c45ce)

**Comment by maxhu08** [comment]
That has to do with the browser, firefox handles opacity and blur differently than chromium. It seems to happen to me on firefox as well, but if I place my cursor over the bookmark, it goes away.

I don't have the ability to fix this since this has to do with how the browser renders things, which I can't control.

**Comment by richmailYT** [comment]
I couldn't reproduce this on FireFox 127.0.2, windows 10

**Comment by maxhu08** [comment]
Other extensions aren't allowed to load on the new tab page, it should just be a bug with how firefox renders stuff
